# Generated by Django 5.2.2 on 2026-06-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('badge_text', models.CharField(blank=True, help_text='e.g. SPECIAL OFFER, FLASH SALE', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('btn_text', models.CharField(default='Shop Now', max_length=50)),
                ('btn_link', models.CharField(default='/', max_length=200)),
                ('bg_color', models.CharField(default='linear-gradient(135deg,#f97316,#ef4444)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, default='Welcome to Gazitrade — your trusted online store for genuine products delivered fast across Bangladesh.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='owner_name',
            field=models.CharField(blank=True, default='Emon', max_length=100),
        ),
    ]
