# Generated by Django 5.2.2 on 2026-06-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_populate_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='btn_link',
            field=models.CharField(default='/products/', max_length=200),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='btn_link',
            field=models.CharField(default='/products/', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, default='Welcome to Gazitrade — your trusted online dropshipping store. We offer genuine products across fashion, electronics, home & lifestyle, and more, delivered fast anywhere in Bangladesh. No advance payment. Cash on delivery always.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='owner_name',
            field=models.CharField(blank=True, default='Gazi Eman Mahmud', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Gazitrade', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Your Trusted BD Shop', max_length=200),
        ),
    ]
